version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  Build:
    docker:
      - image: cimg/node:16.10
    steps:
      - node/install
      - checkout
      - run:
         name: Frontend Build
         command: npm run frontend:build
      - run:
         name: Backend Build
         command: npm run api:build
      - run:
         name: Frontend Install
         command: npm run frontend:install
      - run:
         name: Backend Install
         command: npm run api:install
      - run:
         name: Frontend Deploy
         command: npm run frontend:deploy
      

workflows:
  sample:
    jobs:
      - Build
