
version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@1.3.1

jobs:
   
    docker:
      - image: cimg/node:16.10
   
    steps:
       
     - node/install
     - checkout
     - aws-cli/setup
     
     - node/install-packages:
          pkg-manager: npm
     - run:
         name: Frontend Install
         command: npm run frontend:install
         
         - run:
         name: Backend Install
         command: npm run api:install
         - run:
         name: Frontend Build
         command: npm run frontend:build

         - run:
         name: Backend build
         command: npm run api:build

         - run:
         name: Frontend deploy
         command: npm run frontend:depoly



workflows:
  
  sample:
    jobs:
      - Install
      - Build
      
